=== qinyuan/JavaExample/src/main/resources/metrics-filter.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:metrics-filter="http://org.qinyuan15.com/schema/test-schema"
           targetNamespace="http://org.qinyuan15.com/schema/test-schema"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="metrics-filter">
        <xs:complexType>
            <xs:all>
                <xs:element ref="metrics-filter:stats" minOccurs="0"/>
                <xs:element ref="metrics-filter:statistic" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="stats">
        <xs:complexType>
            <xs:all>
                <xs:element ref="metrics-filter:include" minOccurs="0"/>
                <xs:element ref="metrics-filter:exclude" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="statistic">
        <xs:complexType>
            <xs:all>
                <xs:element ref="metrics-filter:include" minOccurs="0"/>
                <xs:element ref="metrics-filter:exclude" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="include">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="start-with" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="end-with" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="regex" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="exclude">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="start-with" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="end-with" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="regex" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== qinyuan/JavaExample/src/main/resources/metrics-filter.xml
<?xml version="1.0" encoding="utf-8"?>
<metrics-filter xmlns="metrics-filter.xsd"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="metrics-filter.xsd
                                metrics-filter.xsd">

    <statistic>
        <include>
            <start-with>test</start-with>
            <start-with>me</start-with>
        </include>
        <exclude>
            <start-with>goto</start-with>
            <start-with>next</start-with>
        </exclude>
    </statistic>
    <stats>
        <include>
            <start-with>test</start-with>
            <start-with>me</start-with>
        </include>
        <exclude>
            <start-with>goto</start-with>
            <start-with>next</start-with>
        </exclude>
    </stats>

</metrics-filter>
